### ISSUE TITLE
Possibility to check whether other microfrontend exists 

### ISSUE THREAD

**Issue by golojg** [kyma-project/luigi#127]
**Description**

It would be great if Luigi will provide possibility to check whether other microfrontend exists. Someting like:
`
LuigiClient.linkManager()
            .path("/project/other-module")
            .exists()
`

**Reasons**

We want show option to navigate to other microfrontend only if it is available.

**Comment by kwiatekus** [comment]
A way to go:
make an async call to the main application to check if the target node exists (is configured, not if its target view is up and running)

Do we want to include dynamic nodes in the check? From one point of view it might be a performance issue to resolve all (also dynamic) nodes of the examined path. On the other hand it's not really nice to only check statically defined nodes.

**Comment by kwiatekus** [comment]
It should work also for the  paths relative to the current location
