### ISSUE TITLE
mockAuth not working and also not found enough documentation on it.

### ISSUE THREAD

**Issue by webdesignermumbai** [kyma-project/luigi#134]
I like this project but found more scope for documentation.

I tried by adding mockAuth setting in basicConfiguration.js 
But its loading overview page directly without login page.

    Luigi.setConfig({
      auth: {
        use: 'mockAuth',
        mockAuth: {
          authorizeUrl: `${window.location.origin}/assets/auth-mock/login-mock.html`,
          logoutUrl: `${window.location.origin}/assets/auth-mock/logout-mock.html`,
          post_logout_redirect_uri: '/logout.html',
          authorizeMethod: 'GET',
          oAuthData: {
            client_id: 'egDuozijY5SVr0NSIowUP1dT6RVqHnlp'
          }
        }

please let me know if something more to configure to open authorizeUrl (login-mock.html) in application before overview page.

Please help me or guide me to use above mockAuth features.

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by maxmarkus** [comment]
Your settings are fine.

I think it is ignored because `sampleConfiguration.js` is referenced in `index.html` instead of `basicConfiguration.js`. 

I've identified some more issues with the basic configuration and the dev server for path routing, so we need to rely on hash routing for now. Theses issues will be fixed when closing this issue.

After changing index.html to reference `basicConfiguration.js` and adding the configuration below, start dev server with `npm run start`. 

    Luigi.setConfig({
      auth: {
        use: 'mockAuth',
        mockAuth: {
          authorizeUrl: `${window.location.origin}/assets/auth-mock/login-mock.html`,
          logoutUrl: `${window.location.origin}/assets/auth-mock/logout-mock.html`,
          post_logout_redirect_uri: '/logout.html',
          authorizeMethod: 'GET',
          oAuthData: {
            client_id: 'egDuozijY5SVr0NSIowUP1dT6RVqHnlp'
          }
        }
      },
      navigation: {
        nodes: () => [
          {
            pathSegment: 'home',
            label: 'Home',
            children: [
              {
                pathSegment: 'hw',
                label: 'Hello World!',
                viewUrl: '/assets/sampleexternal.html'
              },
              {
                pathSegment: 'one',
                label: 'Section one',
                viewUrl: '/assets/sampleexternal.html#one'
              },
              {
                pathSegment: 'two',
                label: 'Section two',
                viewUrl: '/assets/sampleexternal.html#two'
              }
            ]
          }
        ]
      },
      routing: {
        /**
         * Development:
         * For hash routing, set to true and run `npm run start`
         * For path routing, set to false and run `npm run startWebpack`
         */
        useHashRouting: true
      }
    });

**Comment by webdesignermumbai** [comment]
Thanks for correcting, but still finding difficulty on mockAuth its not opening login page, everytime its directly open inner Hello World page.

Used below code
`auth: {
    use: 'mockAuth',
    mockAuth: {
      authorizeUrl: `${window.location.origin}/assets/auth-mock/login-mock.html`,
      logoutUrl: `${window.location.origin}/assets/auth-mock/logout-mock.html`,
      post_logout_redirect_uri: '/logout.html',
      authorizeMethod: 'GET',
      oAuthData: {
        client_id: 'egDuozijY5SVr0NSIowUP1dT6RVqHnlp'
      }
    }
  },`

**Is there way of enabling login page in luigi?**

**Comment by maxmarkus** [comment]
Have you tried to log out and then load the page again? Maybe you have some "valid" auth token in local storage, try to clear it, please.
As soon as you have _auth.use_ defined it loads login page automatically unless you are already logged in previously.

Btw, feel free to join us in Slack, you find the link on the top right navigation at https://kyma-project.io

**Comment by webdesignermumbai** [comment]
Thanks, @maxmarkus it working now after taking latest files.
Your support was excellent. I really have to appreciate that.
