### ISSUE TITLE
Make logo and title in Luigi configurable

### ISSUE THREAD

**Issue by webdesignermumbai** [kyma-project/luigi#139]
Is it possible to make logo and title editable in Luigi configatation

**Reasons**
It will help to build brand trust

**Comment by kwiatekus** [comment]
Provide convenient configuration attributes for logo and title.
The fav icon and html document title should be changed as well.

**Comment by kwiatekus** [comment]
tricky part here : assure its configurable in runtime (console will consume the values for those attributes from an js asset file)
