### ISSUE TITLE
Top-right context switcher navigation dropdown

### ISSUE THREAD

**Issue by hardl** [kyma-project/luigi#147]
In order to model the context concepts for our various luigi customers (environment selector in kyma, tenant switcher in cds, etc.), we need to have a context switcher ui control, see "Context Switcher" on https://sap.github.io/fundamental/demo-pages/sidebar-app-demo.html

**Comment by jesusreal** [comment]
Still two issues:
- If path starts with some value as the context switcher `parentNodePath`, the remaining part is considered by context switcher as a subpath.
- if you navigate to `environments`, the route is set to `environments/:environmentId`, which is obviously wrong.

**Comment by maxmarkus** [comment]
Options should get lazy loaded only on click. If there are no options loaded, use FallbackLabelResolver to get the label for the closed context switcher.
