### ISSUE TITLE
Improve luigi sample application installation guide

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/luigi#156]
Improve and update the Luigi Angular sample application.

**Comment by parostatkiem** [comment]
Please describe what exactly wasn't working for you. I assume you followed the guide from `core/examples/luigi-sample-angular/README.md`, right?

**Comment by parostatkiem** [comment]
I've just cloned a fresh Luigi repo and followed the guide step by step. It works 🌝

**Comment by bszwarc** [comment]
Yes this is correct I did it as well :) Actually it was about a naming issue, which was fixed in the meantime in another issue and now it properly says `extendedConfiguration.js`. 
However, I would add some improvements purely on the docu side - some active voice instead of passive and so on.
