### ISSUE TITLE
Improve Luigi Client API (-related) documentation 

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/luigi#170]
A task for improving Luigi Client (-related) documentation.
Documents to improve:
- https://github.com/kyma-project/luigi/tree/master/client should refer to the autogenerated luigi client api documentation
- https://github.com/kyma-project/luigi/blob/master/docs/luigi-client-api.md . Here we need some more general improvements (but let's wait for this one: https://app.zenhub.com/workspace/o/kyma-project/luigi/issues/155 to be closed to avoid merging conflicts).

**Comment by kwiatekus** [comment]
Few improvements introduced within https://github.com/kyma-project/luigi/pull/197
