### ISSUE TITLE
Rename 'builderCompatibilityMode'

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/luigi#188]
**Description**

Rename `builderCompatibilityMode` to sth else, in example `disableSPARouting`

**Reasons**

`builderCompatibilityMode` is confusing and doesnt say anything to people who dont know what builder is

**Comment by pekura** [comment]
The 'builderCompatibilityMode' does more than disabling spa routing - it really simulates yaas Builder environment to some extent so the name is justified. 

Let's keep this setting but not promote it to everybody, just to known customers migrating views from yaas Builder.

Let's introduce a new flag with a good name for what we want it to be doing - like view isolation on every navigation.

**Comment by kwiatekus** [comment]
global 'navigation' flag
```
navigation : {
 forceViewIsolation : true
}
```
