### ISSUE TITLE
Link to most recently released versions of the .md files from the main readme file

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/luigi#218]
**Description**

As a Sebastian, I want to read manuals that correspond to the latest published version. Reading about stuff that is not yet published, but merged to master (still unavailable) is confusing.

Find a way and implement easy mechanism to link to (latest) tagged version of md documents

**Reasons**

We want to reference to the documents describing the latest published version, NOT the ones that made it to master. 

In example:
https://github.com/kyma-project/luigi/blob/{latest}/docs/application-setup.md

**Comment by hardl** [comment]
obsolete
