### ISSUE TITLE
Add basic Doc's 

### ISSUE THREAD

**Issue by GauSim** [kyma-project/luigi#22]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**

please add some basics doc's on: 

- `LuigiClient` core public API, maybe you can just have better inline code docs and link them into a webpage or something. 

- Add a getting started guide to integrate a new app. 

**Reasons**

Helps with getting started.

**Comment by kwiatekus** [comment]
Hi, 
The second point is done. Please refer to the getting started documentation : https://github.com/kyma-project/luigi/blob/master/docs/application-setup.md

**Comment by kwiatekus** [comment]
We want to have reference documentation for LuigiClient API.
The documentation content should be generated automatically by 'js api doc' generation tool.

We need to find a good place for this documentation

**Comment by jesusreal** [comment]
Replaced current Luigi Client API docu with an inline, autogenerated documentation.
