### ISSUE TITLE
Top Header responsiveness problems in Chrome

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/luigi#269]
Elements inside `fd-shellbar__group` are not good positioned for certain widths in Chrome.

Overlapping with context switcher:
![Screen Shot 2018-12-05 at 14.24.06.png](https://images.zenhubusercontent.com/5b8689081dd32d2cc77238ca/f16bb42b-7066-45e6-8ecf-93021b4ea8af)

Title bellow the logo:
![Screen Shot 2018-12-05 at 14.24.17.png](https://images.zenhubusercontent.com/5b8689081dd32d2cc77238ca/2607e117-0f67-4b7c-8723-80dff336432d)

**Comment by dariadomagala** [comment]
For the top navigation nodes, we use fiori-fundamentals shellbar which checks the screen size to display either the dropdown or the regular list. It doesn't have the maximum container width or something like that, so no matter how many nodes we will have, the dropdown won't appear on bigger screens and our top navigation will break.
So, we would need to use our own logic for that or contribute to fiori-fundamentals.

Moving this ticket back to 'to do' as it's not a quick fix, and it doesn't have the highest priority for the Luigification epic.

**Comment by marynaKhromova** [comment]
The issue was fixed within this task https://github.com/kyma-project/console/issues/580
