### ISSUE TITLE
Routing to a parent of dynamic node with tailing slash '/' doesnt work properly

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/luigi#274]
**Description**

Routing to a parent of dynamic node with tailing slash '/' is buggy.
For Example:

In case for path routing, the following routes kill the browser (infinite loop of `navigateTo`):
http://localhost:4200/projects/pr2/users/groups/
http://localhost:4200/environments/

In case of hash routing, for the following routes, alert is shown that a route is not resolved :
http://localhost:4200/#/projects/pr2/users/groups/
http://localhost:4200/#/environments/

**Comment by pekura** [comment]
This issue is fixed by #270 (by the related PR).
