### ISSUE TITLE
Prevent XSS attack by sanitization of params 

### ISSUE THREAD

**Issue by sebarys** [kyma-project/luigi#278]
**Description**

Provided by Luigi values if not sanitized can cause injection of malicious code.

**Proposed mitigation**

Set by user/application query parameters should be sanitized to mitigate possibility of injecting malicious code when using values provided from Luigi e.g. `LuigiClient.getNodeParams()`

**Comment by kwiatekus** [comment]
Please sanitize also url params.

maybe we should have own code for sanitation.

**Comment by maxmarkus** [comment]
Check if this library could be of help https://github.com/yahoo/xss-filters

**Comment by adamdyga** [comment]
I suggest to do it like Angular does: sanitize by default, but provide a way to skip the sanitation.
