### ISSUE TITLE
Angular sample app started with webpack doesn’t have all icons

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/luigi#280]
**Expected result**

Application should be rendered the same way when starting it with angular cli and webpack.

**Actual result**

Application started with webpack doesn’t have all icons.
<img width="141" alt="screen shot 2018-12-07 at 11 35 18" src="https://user-images.githubusercontent.com/40663133/49642900-84da7780-fa14-11e8-8390-f92c4cee9bb2.png">
(Although some of them are rendered properly).

**Steps to reproduce**

Start the Angular sample app using the `npm run startWebpack` command.

**Comment by maxmarkus** [comment]
Will be solved with path routing support within angular-cli, which removes `startWebpack`. Will be resolved by #287
