### ISSUE TITLE
Going to “absolutely” wrong path in path routing doesn’t redirect to the root

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/luigi#281]
**Expected result**

After going to an "absolutely" wrong path when using path routing (e.g. myapp.com/non-existing-path), Luigi should show an error message, and redirect user to the root.

**Actual result**

Going to a wrong path shows an error message, but doesn't redirect to the root.

**Steps to reproduce**

* open a Luigi app with a path routing
* go to a non-existing path
* error is shown but no redirection

**Comment by parostatkiem** [comment]
PR: https://github.com/kyma-project/luigi/pull/310
