### ISSUE TITLE
Error's in application setup docu for luigi

### ISSUE THREAD

**Issue by JohannesDoberer** [kyma-project/luigi#322]
When I follow the steps for creating example apps (non-framework, angular6, sapui5 and vue) there are missing curl statements like 
curl https://raw.githubusercontent.com/kyma-project/Luigi/master/core/examples/luigi-sample-angular/src/assets/basicexternal.html > public/assets/basicexternal.html
and the path or the include of sampleconfig is wrong or it is named externalconfig and referenced in index.html as sampleconfig.js

**Comment by JohannesDoberer** [comment]
depends on #313

**Comment by parostatkiem** [comment]
Did #313 fix that? 
It should have...
