### ISSUE TITLE
Bug in Application setup for Angular 6

### ISSUE THREAD

**Issue by JohannesDoberer** [kyma-project/luigi#323]
When I'm following the steps to create a luigi example with Angular 6 app I got an error on step:
sed 's/"src\/index.html"/"src\/angular.html"/g' angular.json > tmp.json && mv tmp.json angular.json
=>sed: angular.json: No such file or directory
Since then it is not possible to start the server

**Comment by parostatkiem** [comment]
Resolved by: https://github.com/kyma-project/luigi/pull/313
