### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by marynaKhromova** [kyma-project/luigi#328]
- List indentation is unclear for `externalLink` properties: https://github.com/kyma-project/luigi/blob/master/docs/navigation-configuration.md#node-parameters-1

- What is the default value for `sameWindow`? https://github.com/kyma-project/luigi/blob/master/docs/navigation-configuration.md#node-parameters-1

- General Setup is not simple readable, would be great to have here also list: https://github.com/kyma-project/luigi/blob/master/docs/general-settings.md

**Comment by bszwarc** [comment]
I checked the docs.

* the default value for `sameWindow` is false.
* indentation is misleading that's true, I will fix this.
* general settings needs some reworking, preferably to a list of parameters.
