### ISSUE TITLE
Update Bamboo plan for Luigi

### ISSUE THREAD

**Issue by parostatkiem** [kyma-project/luigi#338]
Please update the plan with bundling LuigiClient, the same way as it's already done for LuigiCore.

```
npm run bundle
``` 
needs to be executed in `/client` (the same way as it's for `/core`).

Thank you :)

**Comment by jesusreal** [comment]
I checked the changes done to Bamboo plan and confronted it to implementation on #325. It looks good to me.

**Comment by y-kkamil** [comment]
waits for #325 to be corrected. 
for now i have disabled luigi-client bundle specific tasks
