### ISSUE TITLE
Mobile & Tablet Responsiveness

### ISSUE THREAD

**Issue by santoshkorigit** [kyma-project/luigi#369]
**Description**
I found Luigi is not responsive for mobile & tablets devices, but SAP Fiori is compatible with responsive grid system. So it will great if Luigi team share there plan on this required Responsiveness feature, which will add good usability and Increase reach to customers and clients on smaller devices.

So it will be helpful, if you share your road-map or plan for luigi responsiveness.

**Reasons**
To avoid the unnecessary resizing, scrolling, zooming, or panning that occurs with luigi that have not been optimized for different devices. It is often very difficult to navigate, and it may even cost to potential customers who become frustrated with trying to figure out how to do something.

**Attachments**
![localhost_4300_projects_pr1 galaxy note 3](https://user-images.githubusercontent.com/3500916/51522974-9e167680-1e50-11e9-83f7-4aff9658b62b.png)
![localhost_4300_projects_pr1 ipad](https://user-images.githubusercontent.com/3500916/51522976-9e167680-1e50-11e9-8ec6-4e6707a7924d.png)
![localhost_4300_overview iphone x](https://user-images.githubusercontent.com/3500916/51522977-9eaf0d00-1e50-11e9-9e3b-a0baecca715d.png)

**Comment by kwiatekus** [comment]
We fixed some of the responsiveness problems.

The request for documentation is covered by the following issue.
https://app.zenhub.com/workspace/o/kyma-project/luigi/issues/465

**Comment by santoshkorigit** [comment]
Thanks @kwiatekus & Luigi team :) 
So in which release i can expect this!
