### ISSUE TITLE
Reload microfrontend when clicking on selected node

### ISSUE THREAD

**Issue by hardl** [kyma-project/luigi#379]
Currently, if the user clicks on a node which is selected, there is no effect, so a user has to click "somewhere else" and then again on the node if he has to trigger a refresh on the microfrontend or refresh the whole page.

AC: 
* when clicking on selected node, microfrontend should reload

**Comment by maxmarkus** [comment]
Should we trigger loading spinner? (quite some work/refactoring required) otherwise this task is super small.
