### ISSUE TITLE
Generic alerts: fix issues in links to relative paths

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/luigi#398]
There are 2 issues with links to relative paths in generic alerts:
- If there is also an absolute link in the alert and we navigate to it first, then navigating to the relative link will not work anymore.
- If we click twice a relative link in the alert

In both cases we get an error alert since the path is not found. 

The issue could be solved by transforming the relative path internally to an absolute path

**Comment by JohannesDoberer** [comment]
already solved
