### ISSUE TITLE
Alert messages improvements

### ISSUE THREAD

**Issue by kstrek** [kyma-project/luigi#434]
Hello,

I would like to propose two impovements to alert messages that (I think) would improve overall user experience:

- Subsequent alert boxes should not override previous ones. It might result in some of messages being overlooked by user if multiple alerts are shown in short time.

- Alert messages should be closed automatically after certain amount of time. It's a common practice in many applications and in most cases that's the behavior expected by users.

Ideally both of those features could be configurable (both on/off and time to automatically close alert) simply by adding another parameters to [showAlert](https://github.com/kyma-project/luigi/blob/master/docs/luigi-client-api.md#parameters-11) method.

**Comment by corey-aloia-sap** [comment]
I was just about to create an issue for the same thing :) what would be great would be if a user could specify the amount of time to have an Alert message open for, with window.Infinity signalling to never automatically close it.

**Comment by corey-aloia-sap** [comment]
@parostatkiem any reason why this was closed? Was it rejected, completed, or moved into some other issue?

**Comment by maxmarkus** [comment]
Hello @corey-aloia-sap there were improvements that are done in the connected PR, unfortunately we didn't inform you here about these changes. 

Please check the [luigi client showAlert documentation](https://github.com/SAP/luigi/blob/master/docs/luigi-client-api.md#showalert) and see if this fulfils your needs. 

What could be of interest there:
- alerts are stacked 
- `closeAfter` parameter allows setting a close timeout. Default is 0, which leaves the alert open


If there is still something missing, we're happy to receive another feature request.

**Comment by corey-aloia-sap** [comment]
@maxmarkus perfect, thanks!

**Comment by hardl** [comment]
This is the related PR: https://github.com/SAP/luigi/pull/480
Released with 0.4.12
