### ISSUE TITLE
scrolling issue on ios safari

### ISSUE THREAD

**Issue by hardl** [kyma-project/luigi#450]
there is a known issue in safari on ios with iframe scrolling. There are some solutions out there which all work rather semi-optimal, but this one looks promising:

```
.iframeContainer {
			-webkit-overflow-scrolling: touch;
			overflow: auto;
		}
```

**Comment by cftellezc** [comment]
Hi!. I know it is closed but I have some issues with this feature. Does it have to do with this maybe?:  https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling
