### ISSUE TITLE
Landing readme.md for luigi

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/luigi#46]
**Description**

We need:
- a logo
- some nice content describing which problems Luigi solves
- high level diagram

**Reasons**

To give high level overview for the potential users/collaborators about Luigi. 

**Attachments**

[docu_proposal.txt](https://github.com/kyma-project/luigi/files/2360271/docu_proposal.txt)

**Comment by dpolitesap** [comment]
The text refinements discussed with Philipp are complete.
https://github.com/kyma-project/luigi/pull/80/files
