### ISSUE TITLE
Preserve view doesn't work as expected

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/luigi#56]
Preserve view functionality should save the given value and pass it to the previous module view. Right now it saves the value, but doesn't pass it to the previous view properly - this view displays not the last value, but one before that.

1) I call goBack method with value '1' -> nothing is shown in the UI
2) I call goBack method with value '2' -> '1' is shown in the UI
3) I call goBack method with value '3' -> '2' is shown in the UI 
 ...

**Comment by jesusreal** [comment]
This might be a race condition, it looks like we want to send the value before or when we navigate, but we are sending the value afterwards.
