### ISSUE TITLE
Request to make navigation tree collapsible

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/luigi#61]
**Description**

It would be very helpful if the navigation tree is collapsible.
~~If collapsed, only the icons of the navigation nodes should be displayed.~~ will be handled in https://github.com/kyma-project/luigi/issues/453

**Comment by parostatkiem** [comment]
I've done some work on it on my local branch. Please contact me when this task is picked up :)

**Comment by parostatkiem** [comment]
I've lost some of my work on it (wasn't much; mostly CSS). Please do not contact me when this task is picked up :)
