### ISSUE TITLE
Auto-formatting for svelte components

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/luigi#62]
**Description**

For now Prettier auto-formats only .js/.ts/.css files. Svelte components reside in .html files, thus Prettier skips them. Check if it is possible to apply (and implement ) auto-formatting for js snippets inside .html svelte components.

**Comment by maxmarkus** [comment]
Check progress on https://github.com/prettier/prettier/issues/1882 if it is worth to wait for, or implement it and send PR to prettier.

**Comment by parostatkiem** [comment]
This may help:
https://www.npmjs.com/package/prettier-plugin-svelte

We just need to hook it on commit/push and voilà the problem is gone 🍻
