### ISSUE TITLE
Luigi improvements after feedback received

### ISSUE THREAD

**Issue by jesusreal** [kyma-project/luigi#68]
Based on the feedback provided by Artur Nowakowski on https://github.com/kyma-project/luigi/pull/45, I took a deeper look on his proposals, discussed with a team member and decided on action items, and shared with the rest of the team. 

Action items:
- ~Luigi UMD (add some webpack configuration)~ Invalid
- ~Add 2 new simple examples (rename folders and files to follow naming conventions)~ Will add additional example in different issue. Additionally we have documentation instructions describing how to setup luigi applications using different technologies.
-  Optimize initialization (remove interval checking, initialize right after setting the config data)

We can get rid of the interval checking in the main.js of the luigi core and bootstrap the Luigi as a callback function of the Luigi.setConfig() fn

There are still some drawbacks regarding removing the public folder on core repo which don´t make it straightforward, therefore this is out of scope for this task. E.g., a different package.json is still needed for released version, path would be different for all files in public folder except luigi.js.

**Comment by aartek** [comment]
Thanks for reviewing and creating action items!
I just wanted to remind about the possibility of importing authentication callback handler. Currently I have to copy js code from [callback.html](https://github.com/kyma-project/luigi/blob/master/core/public/auth/oauth2/callback.html). I'd rather import the function than copy the whole file. You could also check if it could be achieved in another way i.e by enabling default oauth handler in oauth config. In my PR it was possible to import it. 

Maybe the `Luigi UMD` action item already covers that feature request, but I just wanted to clarify it ;)
