### ISSUE TITLE
Generic alerts and confirmation boxes

### ISSUE THREAD

**Issue by aartek** [kyma-project/luigi#72]
**Description**

Hi, It'd be great to have generic solution to display alerts and confirmation boxes. 

Alerts:
- Types: info, warning, error, success
- Configuration params:
  - Auto close (with timeout) / close with button
  - with/without backdrop 
- support for closing it programaticaly
- I think I won't need it but maybe closing could support callback or opening could return promise resolved after close
- alerts should allow displaying urls. It would be great if could use link manager (use case: display error alert like `Your request failed because extension you tried to use is not enabled. Go to extension ui and enable it first <deeplink to another ui here>`. User clicks link, goes to extension ui, enables extension, clicks back, repeats request, fireworks.gif 😉)

Confirmation boxes:
- list of buttons to display - there may be many use cases, one will want to have "ok" and "cancel" other will want to have "cancel", "save as draft", "save" etc. It should be flexible 
- function which displays popup could return promise, resolved after any button click
- support for closing it programaticaly

**Reasons**
Alerts and confirmation boxes is widely used thing in the user interfaces. Having dedicated mechanism to display them would help developers to provide better user experience, because they would always look and behave the same.

**Comment by jesusreal** [comment]
pr for confirmation modal: https://github.com/kyma-project/luigi/pull/389

There will be another pr for generic alerts.
