### ISSUE TITLE
Authentication improvements - logout and token expiration handling

### ISSUE THREAD

**Issue by aartek** [kyma-project/luigi#73]
**Description**

Hi, it'd be great to have out-of-the box oauth token expiration handling and builtin logout button. 

After token expiration luigi could ask if token should be renewed. Otherwise user should be redirected to the logout page set in the oauth configuration. Please notice that currently it may act weird if there is set the same `redirect_uri` and `logoutUrl` because of the auto-login behavior

```
oAuth2ImplicitGrant: {
                    authorizeUrl: 'http://example.com/oauth/authorize',
                    logoutUrl: 'http://localhost:4200',
                    oAuthData: {
                        client_id: 'my.client',
                        redirect_uri: 'http://localhost:4200',
                        response_type: 'token',
                    }
}
```
 Having the auto-login behavior configurable, would be also a great thing - currently I'm making workarounds to avoid it.

**Reasons**
To have out-of-the-box oauth login support for all use cases - login and logout.

**Comment by kwiatekus** [comment]
@aartek The  configuration of Auto-login will be handled in separate ticket https://github.com/kyma-project/luigi/issues/123

**Comment by kwiatekus** [comment]
@aartek The token renewal will be handled in this ticket: https://github.com/kyma-project/luigi/issues/124
