### ISSUE TITLE
navigation node as a link to an external page

### ISSUE THREAD

**Issue by hardl** [kyma-project/luigi#91]
Introduce a static link node that only has the properties
* label
* category
* externalLinkUrl
* sameWindow 

If a node has a property externalLinkUrl, it is treated as a static link node and all irrelevant properties should be ignored. In the left-side navigation, these nodes should get a dedicated styleclass so they can be later distinguished visually.

**Comment by dariadomagala** [comment]
@parostatkiem AFAIK if it's set to _true_ we should open the external page in the same tab, but not as an iFrame. We already have an option to put it inside iFrame, this is a different functionality - here we want to leave Luigi completely.

**Comment by parostatkiem** [comment]
It's even simplier!

**Comment by hardl** [comment]
It's exactly like Daria said ;) 
And default should be "false".
