### ISSUE TITLE
"Dynamic nodes" feature

### ISSUE THREAD

**Issue by hardl** [kyma-project/luigi#94]
The dynamic node functionality enables the user to specify the path segment not to be a static string but a dynamic value that is then passed to the context of the view.

Two implementation options:
1) as in yaas builder using a dedicated property "dynamic". Its value is used as the key in the context object.
2) convention in existing pathSegment property, e.g. ":"-prefix, so ":context_key"  

See https://devportal.yaas.io/tools/buildersdk/index.html#IntegrateaBuildermodule, section "Dynamic nodes in navigation tree" for more info.

**Comment by kwiatekus** [comment]
- the dynamic segment value should be added to the context (not node params) 
- support  inheritance i.e `/home/:project/:workspace` (both dynamic values should be available for all child nodes)
- dynamic node is the only node on its navigation level.. (avoid static nodes being matched as dynamic ). If static & dynamic node coexist on the same level, we should reject the static one and print a `console.warning` informing about misconfiguration.
- suggested data structure - object within context 
```
context : {
 pathParams: {
key1:"value",
key2: "value2"
}
}
```

**Comment by maxmarkus** [comment]
Not included in normal context to avoid "nested merging" issues.
```
LuigiClient.getPathParams() // is used to fetch the params
```
Alternatively a custom context object can be used for enriching the context
```
{
  context: {
    environment: ':environment' 
  }
}
```
